---
title: "In-class_Ex12"
---

```{r}
pacman::p_load(tmap, sf, sp, caret, stplanr, reshape2, broom, tidyverse)
```

```{r}
odbus<-read_csv("data/aspatial/origin_destination_bus_202210.csv")
```

```{r}
#odbus7_9 <- odbus %>%
 # filter (DAY_TYPE == "WEEKDAY") %>% 
# filter (TIME_PER_HOUR >= 7 &
 # TIME_PER_HOUR <= 9)%>% 
#  group_by (ORIGIN_PT_CODE,
#DESTINATION_PT_CODE) %>%
#summarise(TRIPS = sum (TOTAL_TRIPS))
```

```{r}
#odbus$ORIGIN_PT_CODE <- as.factor(odbus$ORIGIN_PT_CODE)
#odbus$DESTINATION_PT_CODE <-as.factor(odbus$DESTINATION_PT_CODE)
```

```{r}
#write_rds(odbus7_9 , "data/rds/odbus7_9.rds")

```

```{r}
#odbus7_9 <-read_rds("data/rds/odbus7_9.rds")
```

```{r}
#busstop <- st_read(dsn = "data/geospatial",
#    layer="BusStop")
```

```{r}
#mpsz <- st_read(dsn ="data/geospatial",layer = "MPSZ-2019") %>% st_transform(crs = 3414)


```

```{r}
#bustop_mpsz <- st_intersection(busstop, mpsz) %>%
#select(BUS_STOP_N, SUBZONE_C) %>% 
#st_drop_geometry()
```

```{r}
#change to factor type (character field, ordinal scale)
#odbus$ORIGIN_PT_CODE <- as.factor(odbus$ORIGIN_PT_CODE)
#odbus$DESTINATION_PT_CODE <- as.factor(odbus$DESTINATION_PT_CODE)
```

```{r}
#od_data <- left_join(odbus7_9 , busstop_mpsz,
#by = c("ORIGIN PT CODE","BUS_STOP _N")) %%
#rename(ORIGIN_BS = ORIGIN_PT_CODE,
#ORIGIN_SZ = SUBZONE_C,
#DESTIN_BS = DESTINATION_PT_CODE)
```

```{r}
#duplicate <- od_data %>% group_by_al1() %>% filter (n()>1) #%% ungroup ()

#od_data <- unique (od_data)
```

```{r}
#od_data <- od_data %>%
#rename (DESTIN_SZ = SUBZONE_C) %>%
#drop_na ()
```

```{r}
#write_rds(od_data,"data/rds/od_data.rds")
```

```{r}
#tmap_mode("view")
#tmap_options(check.and.fix = TRUE)
#qtm(mpsz)
```

```{r}
#mpsz <-mpsz[order(mpsz$SUBZONE_C),]
#head(mpsz,10)

```

```{r}
#mpsz_sp <-as(mpsz,"Spatial")
```

```{r}
#dist <- spDists(mpsz_sp)
#dist
```

```{r}
#sz_names <-mpsz$SUBZONE_C
```

```{r}
#colnames(dist) <- paste0(sz_names)
#rownames(dist) <- paste0(sz_names)
```

```{r}
#distPair <- melt(dist) %>% #melt works like pivot longer
#  rename(dist= value)
#head(distPair,10)
```

```{r}
#distPairsdist <- ifelse(distPair$dist == 0,
#50, distPairsdist)
```

```{r}
#distPair < distPair %%
#rename (orig = Var1,
#dest = Var2)
```
