---
title: "In-class_Ex07"
---

```{r}
pacman::p_load(sf, spdep, tmap, tidyverse)
```

```{r}
hunan <- st_read(dsn = "data/geospatial", 
                 layer = "Hunan")
```

```{r}
hunan2012 <- read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
GDPPC <- read_csv ("data/aspatial/Hunan_GDPPC.csv")
```

```{r}
GDPPC_st <- spacetime(GDPPC, hunan,
                        .loc_col = "County",
                        .time_col = "Year")
```

```{r}
hunan <- left_join(hunan,hunan2012) %>%
  select(1:4, 7, 15)
```

```{r}
GDPPC_nb <- GDPPC_st %›%

activate ("geometry") %›%

mutate (nb = include_self(
  st_contiguity (geometry)),
  wt - st_weights(nb)) %>%
  
set_nbs("nb*) %>% set_wts("wt")
```

```{r}
_stars <- GDPPC_b %›% group_by (Year) %›%

mutate(gi_star = local_gstar_perm

GDPPC, nb, wt, nsim = 99)) %%

tidyr: : unnest (gi_star)
```

```{r}

cbg <- gi
```

```{r}
basemap <- tm_shape(hunan) +
  tm_polygons() +
  tm_text("NAME_3", size=0.5)

hunan_GDPPC <- qtm(hunan, "GDPPC")
tmap_arrange(basemap, hunan_GDPPC, asp=1, ncol=2)
```

```{r}
wm_q <- hunan_GDPPC %>%
mutate(nb = st_contiguity (geometry),
                wt = st_weights (nb, 
                         style = "W"),
                .before = 1)
```

```{r}
moranI <- global_moran (wm_q$GDPPC,
wm_q$nb, wm_q$wt)
```

```{r}
global_moran_test (wm_q$GDPPC,
wm_q$nb, wm_q$wt)
```

```{r}
set.seed (1234)
```

```{r}
global_moran_perm(wm_q$GDPPC,
                  wm_q$nb,
                  wm_q$wt,
                nsim = 99)
```

```{r}

lisa < - wm_q %>%

  mutate(local_moran - local_moran(

    GDPPC, nb, wt, nsim = 99),
      .before = 1) %>%
unnest (local_moran)

lisa
```

```{r}
tmap_mode ("plot")
tm_shape (lisa) + 
  tm_fill("p_ii") +
  tm_borders (alpha = 0.5)
```

```{r}
tmap_mode("plot")
tm_shape (lisa) + 
  tm_fill("ii") +
  tm_borders (alpha = 0.5) +
  tm_view(set.zoom.limits = C(6,8))
```

```{r}
lisa_sig <- lisa %›%
  filter (p_ii< 0.05)
tmap_mode("plot")
tm_shape(lisa) + 
  tm_polygons() +
  tm_borders (alpha = 0.5) +
tm_shape(lisa_sig) + 
  tm_fill("mean") +
  tm_borders (alpha = 0.4)
```
