---
title: "In-class_Ex10  :Spatial Interaction Models"
---

```{r}
pacman::p_load(sf, spdep, GWmodel, SpatialML, tidyverse,
               tmap, ggpubr, olsrr, devtools, rsample)
```

## Data Import and Prepatation

### Importing geospatial data into R environment

```{r}
mdata <- read_rds("data/aspatial/mdata.rds")
subzone <- st_read(dsn = "data/geospatial", 
                   layer = "MP14_SUBZONE_WEB_PL")

set.seed(123)

reasale_split <- initial_split(mdata,
                               prop = 6.5/10,)
train_data <- training(reasale_split)
test_data <- testing(reasale_split)
```

```{r}
write_rds(train_data, "data/model/train_data.rds")
write_rds(test_data, "data/model/test_data.rds")
```

```{r}
price_mlr <- lm(resale_price ~ floor_area_sqm +
                storey_order + remaining_lease_mths +
                PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                PROX_MRT + PROX_PARK + PROX_MALL +
                PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                WITHIN_1KM_PRISCH, 
                data=train_data)
summary(price_mlr)

```

```{r}
write_rds(price_mlr,"data/model/price_mlr.rds")
```

```{r}
train_data_sp <- as_Spatial(train_data)
train_data_sp
```

```{r}
coords <- st_coordinates(mdata)
coords_train <- st_coordinates(train_data)
coords_test <- st_coordinates(test_data)
```

```{r}
coords_train <- write_rds (coords_train,"data/model/coords_train.rds")
coords_test <- write_rds(coords_test,"data/model/coords_test.rds" )
```

```{r}
#First, we will drop geometry column of the sf data.frame by using 
#st_drop_geometry() #of sf package.
```

```{r}
train_data <- train_data %>% st_drop_geometry()
```

```{r}
set.seed(1234) # random forest
rf <- ranger(resale_price ~ floor_area_sqm +
                storey_order + remaining_lease_mths +
                PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                PROX_MRT + PROX_PARK + PROX_MALL +
                PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                WITHIN_1KM_PRISCH, 
                data=train_data)

```

```{r}
print(rf)
```

```{r}
gwRF_adaptive <- grf(formula = resale_price ~ floor_area_sqm +
                storey_order + remaining_lease_mths +
                PROX_CBD + PROX_ELDERLYCARE + PROX_HAWKER +
                PROX_MRT + PROX_PARK + PROX_MALL +
                PROX_SUPERMARKET + WITHIN_350M_KINDERGARTEN +
                WITHIN_350M_CHILDCARE + WITHIN_350M_BUS +
                WITHIN_1KM_PRISCH, 
                dframe = train_data,
                bw = 55,
                kernel="adaptive",
                coords=coords_train
                )
```

gwRF_adavtive$Glocal.Model$variable.importance
